version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "80:80"
    volumes:
      - .:/src/app
    networks:
      - abc
  postgres:
    image: "postgres:12.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
    networks:
      - abc
  adminer:
    image: "adminer:4.7.5"
    ports:
      - "8080:8080"
    environment:
      - PMA_HOST= postgres
    networks:
      - abc

volumes:
  volumes1:
  volumes2:

networks:
  abc:
    driver: bridge